### ISSUE TITLE
usage question

### ISSUE THREAD

**Issue by kkuo** [awslabs/aws-cfn-lint-visual-studio-code#15]
How do you make it start working? Opening a YAML file doesn't trigger auto linting and there are no entries in the command palette for this plugin.

**Comment by cmmeyer** [comment]
Hi, @kkuo, the linter triggers of the Version string in your template. For YAML that would be:
`AWSTemplateFormatVersion: "2010-09-09"`

This was the best way we found to identify a CloudFormation template over a regular YAML file.  Linting is not real time -- you will need to save the document to trigger linting.

**Comment by tasiogr** [comment]
I get this error:

`Unable to start cfn-lint (Error: spawn cfn-lint ENOENT). Is cfn-lint installed correctly?`

It is installed correctly and I can run it using the terminal.

**Comment by edjackson-wf** [comment]
@cmmeyer This is true, however....

When `isValidating[uri]` is set to `true` in server.ts (line 114), and then the regex check for the `AWSTemplateVersion` line fails, `isValidating` never gets set back to false. It will display "Is CFN: false" in the server console, and subsequent runs will return immediately (line 111).

If the `AWSTemplateVersion` line is then added, the file still won't validate, because it thinks it's already validating.

Until I looked at the code, I also thought it was broken, because the following workflow produces unexpected results:

1. In explorer sidebar, click the "New File" button
1. Enter "foo.yaml" for the filename
1. Observe "Running cfn-lint..." followed by "Is CFN: false" in the server console
1. Add a correct `AWSTemplateFormatVersion` line and save
1. Observe "Running cfn-lint..." and no further output

Thanks for this plugin and `cfn-lint`, they've saved me a lot of failed CloudFormation runs.

**Comment by kddejong** [comment]
Thanks.  I will take a look as this shouldn’t happen.
