### ISSUE TITLE
Add support for nodejs12.x

### ISSUE THREAD

**Issue by flatherskevin** [awslabs/aws-cfn-lint-visual-studio-code#72]
AWS now supports nodejs12.x as a runtime, but linting is throwing an error that it is not supported.

**Comment by kddejong** [comment]
You need to update your version of cfn-lint since we use that package to do the actual linting.
https://github.com/aws-cloudformation/cfn-python-lint#pip-install

Included as of version [v0.25.2](https://github.com/aws-cloudformation/cfn-python-lint/blob/master/CHANGELOG.md#0252)
Included with PR [1204](https://github.com/aws-cloudformation/cfn-python-lint/pull/1204)

**Comment by flatherskevin** [comment]
Thank you! This can be closed then
